export const theme = {
  colors: {
    navy: "#0B2040",
    navyMid: "#132E54",
    blue: "#1A5FAC",
    blueLight: "#2E7ECC",
    orange: "#E07B2D",
    orangeHover: "#CC6A1F",
    gold: "#D9A441",
    teal: "#0D8A8F",
    tealSoft: "#E1F4F3",
    seafoam: "#E1F4F3",
    sand: "#F4EEE3",
    sandLight: "#FAF7F2",
    cream: "#FFFDF8",
    white: "#FFFFFF",
    textDark: "#161616",
    textBody: "#2C2C2C",
    textMid: "#555555",
    textSoft: "#7A7A7A",
    border: "#E2DBCE",
    borderLight: "#EDE8DF",
  },
  fonts: {
    heading: '"Plus Jakarta Sans", sans-serif',
    body: '"Plus Jakarta Sans", sans-serif',
  },
  radii: {
    card: "14px",
    button: "8px",
    pill: "20px",
    input: "8px",
  },
  spacing: {
    sectionPaddingY: "60px",
    sectionPaddingX: "24px",
    maxWidth: "1100px",
    maxWidthNarrow: "680px",
  },
} as const;
